import './globals.css'
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import { Inter } from 'next/font/google'
import MyProvider from '@/provider/Provider'
import MotionContainer from '@/components/MotionContainer';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MyProvider> 
        <MotionContainer>
          {children} 
        </MotionContainer>
        </MyProvider>      
    
      </body>
    </html>
  )
}
